#!/usr/bin/env python3

import os
import glob
import argparse
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


def mean_pi(file_path):
    df = pd.read_csv(file_path, sep="\t")
    return df.iloc[:, -1].mean()


def read_tajima(file_path):
    df = pd.read_csv(file_path, sep="\t")
    return df["TajimaD"].mean()


def add_cumulative_position(df, window_size=10000):
    """
    Cria posição cumulativa ao longo do genoma.
    Funciona independentemente do formato exato do vcftools.
    """

    df = df.copy()

    # Normalizar nomes de colunas (remover espaços invisíveis)
    df.columns = df.columns.str.strip()

    # Verificar colunas essenciais
    if "CHROM" not in df.columns:
        raise ValueError("Column CHROM not found in file.")

    if "BIN_START" not in df.columns:
        raise ValueError("Column BIN_START not found in file.")

    # Se não houver BIN_END, reconstruir
    if "BIN_END" not in df.columns:
        df["BIN_END"] = df["BIN_START"] + window_size

    # Ordenar corretamente
    df = df.sort_values(["CHROM", "BIN_START"])

    # Calcular tamanho de cada cromossomo
    chrom_sizes = (
        df.groupby("CHROM")["BIN_END"]
        .max()
        .reset_index()
        .sort_values("CHROM")
    )

    cumulative_offsets = {}
    offset = 0

    for _, row in chrom_sizes.iterrows():
        chrom = row["CHROM"]
        cumulative_offsets[chrom] = offset
        offset += row["BIN_END"]

    # Criar posição cumulativa
    df["CUM_POS"] = df.apply(
        lambda row: row["BIN_START"] + cumulative_offsets[row["CHROM"]],
        axis=1
    )

    return df


def main():

    parser = argparse.ArgumentParser(
        description="Generate cumulative diversity PDF report"
    )

    parser.add_argument(
        "-i", "--input_dir",
        required=True,
        help="Directory generated by run_diversity_pipeline.py"
    )

    parser.add_argument(
        "-o", "--output",
        default="FINAL_DIVERSITY_REPORT.pdf",
        help="Output PDF name"
    )

    args = parser.parse_args()

    base_dir = args.input_dir
    output_pdf = args.output

    if not os.path.isdir(base_dir):
        raise Exception("Input directory does not exist.")

    groups = sorted([
        d for d in os.listdir(base_dir)
        if os.path.isdir(os.path.join(base_dir, d))
    ])

    summary = []

    for group in groups:

        group_path = os.path.join(base_dir, group)

        pi_files = glob.glob(os.path.join(group_path, "*_pi.sites.pi"))
        taj_files = glob.glob(os.path.join(group_path, "*_tajima.Tajima.D"))

        if not pi_files or not taj_files:
            continue

        pi_mean = mean_pi(pi_files[0])
        taj_mean = read_tajima(taj_files[0])

        summary.append([group, pi_mean, taj_mean])

    summary_df = pd.DataFrame(
        summary,
        columns=["Group", "Pi_mean", "TajimaD_mean"]
    )

    summary_df.to_csv("diversity_summary.csv", index=False)

    with PdfPages(output_pdf) as pdf:

        # ===== π GLOBAL =====
        plt.figure()
        plt.bar(summary_df["Group"], summary_df["Pi_mean"])
        plt.xticks(rotation=45)
        plt.title("Global Nucleotide Diversity (π)")
        plt.ylabel("π")
        pdf.savefig()
        plt.close()

        # ===== Tajima GLOBAL =====
        plt.figure()
        plt.bar(summary_df["Group"], summary_df["TajimaD_mean"])
        plt.xticks(rotation=45)
        plt.title("Global Tajima's D")
        plt.ylabel("Tajima's D")
        pdf.savefig()
        plt.close()

        # ===== Perfis cumulativos =====
        for group in groups:

            group_path = os.path.join(base_dir, group)

            pi_win = glob.glob(os.path.join(group_path, "*_pi_10kb.windowed.pi"))
            taj_win = glob.glob(os.path.join(group_path, "*_tajima_10kb.Tajima.D"))

            if not pi_win or not taj_win:
                continue

            df_pi = pd.read_csv(pi_win[0], sep="\t")
            df_taj = pd.read_csv(taj_win[0], sep="\t")

            df_pi = add_cumulative_position(df_pi)
            df_taj = add_cumulative_position(df_taj)

            # π cumulativo
            plt.figure(figsize=(12,4))
            plt.scatter(df_pi["CUM_POS"], df_pi["PI"], s=5)
            plt.title(f"{group} - π (10kb windows, cumulative)")
            plt.xlabel("Genomic position (cumulative)")
            plt.ylabel("π")
            pdf.savefig()
            plt.close()

            # Tajima cumulativo
            plt.figure(figsize=(12,4))
            plt.scatter(df_taj["CUM_POS"], df_taj["TajimaD"], s=5)
            plt.title(f"{group} - Tajima's D (10kb windows, cumulative)")
            plt.xlabel("Genomic position (cumulative)")
            plt.ylabel("Tajima's D")
            pdf.savefig()
            plt.close()

    print("Report generated:", output_pdf)
    print("Summary table saved as diversity_summary.csv")


if __name__ == "__main__":
    main()